// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKdm9EenE3_v2HkPH5BIzlzrsLVQ29gNQ',
    appId: '1:960892822756:web:fc1af4c05b1e134ca038f1',
    messagingSenderId: '960892822756',
    projectId: 'push-notification-5d1ed',
    authDomain: 'push-notification-5d1ed.firebaseapp.com',
    storageBucket: 'push-notification-5d1ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHptmNkvXwoCZuX-pPpBPqyU74xbLuGTc',
    appId: '1:960892822756:android:288bf46a43609790a038f1',
    messagingSenderId: '960892822756',
    projectId: 'push-notification-5d1ed',
    storageBucket: 'push-notification-5d1ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJeRLnn2nnElkS0cCAfbmuD2uSX_3QSoU',
    appId: '1:960892822756:ios:d27e594c80c1afb8a038f1',
    messagingSenderId: '960892822756',
    projectId: 'push-notification-5d1ed',
    storageBucket: 'push-notification-5d1ed.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJeRLnn2nnElkS0cCAfbmuD2uSX_3QSoU',
    appId: '1:960892822756:ios:8d7e389248b9759ba038f1',
    messagingSenderId: '960892822756',
    projectId: 'push-notification-5d1ed',
    storageBucket: 'push-notification-5d1ed.appspot.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
